nsite:
  _initState: HOME
  _endState: RETURN
  _states:
    - NAME
    - HOME
    - ITEMS
    - CART
    - PAYMENTED
    - EXTRA
  _events:
    - ITEMS_BUTTON
    - PRODUCT_ADD
    - FINISH
#状态流转集合定义
  _transition:
  - source: "HOME"
    target: "ITEMS"
    event: "ITEMS_BUTTON"
  - source: "ITEMS"
    target: "CART"
    event: "PRODUCT_ADD"
  - source: "CART"
    target: "PAYMENTED"
    event: "FINISH"
# REDIS (RedisProperties)
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0