Nsite:
  states: STATE_1,STATE_2,STATE_3;
  events: EVENT_1,EVENT_2,EVENT_3;

# REDIS (RedisProperties)
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0